apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.foocontroller.k8s.io
  labels:
    app: foo
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: foocontroller.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: foo-apiserver
    namespace: default
  version: v1alpha1
---
apiVersion: v1
kind: Service
metadata:
  name: foo-apiserver
  namespace: default
  labels:
    app: foo
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: foo
