# register to intercept foo CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.foocontroller.k8s.io
webhooks:
- name: admission.foocontroller.k8s.io
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.foocontroller.k8s.io/v1alpha1/admissionreviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - foocontroller.k8s.io
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail
